### ISSUE TITLE
Using beta functionality for web_server_network_access_control

### ISSUE THREAD

**Issue by ranjitk-burwood** [terraform-google-modules/terraform-google-composer#14]
I have been attempting to use the underlying main.tf code and integrating the web_server_network_access_control configuration block (beta function) to limit what IP addresses have access to the Apache Airflow UI.

I have been able to successfully do this where I can add whitelisted IP addresses, update in place, but I can't seem to get rid of all IP addresses when passing in a blank list.

For example I can whitelist one IP address, add a second IP address, remove the second IP address, but if I pass in a blank list to get rid of the first IP address Terraform will not set those values to `null` in order to remove that whitelist.

Child module main.tf

```
    web_server_network_access_control {
      dynamic "allowed_ip_range" {
        for_each = var.allowed_ip_range 
        content {
          value       = lookup(allowed_ip_range.value, "value", null)
          description = lookup(allowed_ip_range.value, "description", null)
        }
      }
    }
```

Child module variables.tf
```
variable "allowed_ip_range" {
  description = "The IP ranges which are allowed to access the Apache Airflow Web Server UI."
  type        = list(map(string))
  default     = []
}
```

Am I missing something within my dynamic block to have Terraform remove the resource attribute or is this something that doesn't work due to the attribute being a beta function?

**Comment by morgante** [comment]
Your code looks correct, so I suspect this is either a provider or API issue. Please open an issue on the provider.

**Comment by ranjitk-burwood** [comment]
Thanks @morgante, I opened up an issue. Link for anyone that wants to follow.

https://github.com/hashicorp/terraform-provider-google/issues/9224
