### ISSUE TITLE
encryption_config  block is missing

### ISSUE THREAD

**Issue by jitum** [terraform-google-modules/terraform-google-composer#15]
Can you update this module to support CMEK. We see in terraform resource documentation encryption_config  block is there, but in module we dont see such option.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/composer_environment#kms_key_name

**Comment by morgante** [comment]
We're happy to accept a pull request adding this, but don't currently have time to prioritize adding it directly.
