### ISSUE TITLE
Update README.md to no longer include composer_sa 

### ISSUE THREAD

**Issue by aabhassharma** [terraform-google-modules/terraform-google-composer#19]
Commit 549ba6224c3e015028bffbf7fd204313179022d9 removed composer_sa as a top level required module input.
Reflect the same in README.md.

I tried pushing up a PR to address this but was blocked on perms unfortunately. 

```
diff --git a/README.md b/README.md
index 99007cd..c3ef924 100644
--- a/README.md
+++ b/README.md
@@ -18,7 +18,6 @@ module "composer" {
   project_id        = "<PROJECT ID>"
   region            = "us-central1"
   composer_env_name = "composer-env-test"
-  composer_sa       = "project-service-account@<PROJECT_ID>.iam.gserviceaccount.com"
   network           = "test-network"
   subnetwork        = "composer-subnet"
 }
```

**Comment by morgante** [comment]
Thanks! You should fork and submit a pull request from there: https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by aabhassharma** [comment]
Great, here you go. 
https://github.com/terraform-google-modules/terraform-google-composer/pull/20

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-google-composer/pull/20
