### ISSUE TITLE
Non us-central1 zones aren't supported?

### ISSUE THREAD

**Issue by voycey** [terraform-google-modules/terraform-google-composer#26]
Terraform version: 1.0.11

Basic repro:

```
module "composer" {
  source  = "terraform-google-modules/composer/google"
  version = "~> 2.0"

  project_id        = var.gcp_project_id
  region            = "australia-southeast1"

  composer_env_name = "airflow-${var.stage}"
  network           = "default"
  subnetwork        = "default"
}
```

Running this gets me:

  ```
│ Error: googleapi: Error 400: Found 2 problems:
  │       1) Provided zone [projects/tymlez-platform-328903/zones/us-central1-f] must be contained within Composer location [australia-southeast1].
  │       2) Provided subnetwork [projects/tymlez-platform-328903/regions/us-central1/subnetworks/default] must match Composer location [australia-southeast1]., badRequest
  │
  │   with module.pipelines.module.composer.module.composer-environment.google_composer_environment.composer_env,
  │   on .terraform/modules/pipelines.composer/modules/create_environment/main.tf line 22, in resource "google_composer_environment" "composer_env":
  │   22: resource "google_composer_environment" "composer_env" {
```

I try and add in subnetwork_region to solve the above and I get:
╷
```
│ Error: Unsupported argument
│
│   on modules/pipelines/pipelines.tf line 11, in module "composer":
│   11:   subnetwork_region = "australia-southeast1"
│
│ An argument named "subnetwork_region" is not expected here.

```

How can I get this running in australia-southeast1?

**Comment by voycey** [comment]
I am pretty sure this PR solves my issue: https://github.com/terraform-google-modules/terraform-google-composer/pull/25

I have created the code locally that includes the zone as a top level variable and its working fine.

**Comment by NickMcCoyCDP** [comment]
@voycey Do you have an available copy of the change(s) you made? After trying with that PR and adjusting the default variable I'm not having any luck.

**Comment by voycey** [comment]
I cant break out a diff of them but basically you have to add in zone and possibly subnetwork to main.tf and variables.tf just as was done here:

https://github.com/terraform-google-modules/terraform-google-composer/pull/25/commits/aee8228ace9e6b237663fb3a3b73433ae725889c#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbbR28
