### ISSUE TITLE
Module not in Terraform Registry

### ISSUE THREAD

**Issue by ipv1337** [terraform-google-modules/terraform-google-composer#3]
Any idea when this module will make it into the Terraform Registry? We're trying to leverage CFT to build out our Composer projects and using this module throws errors like the one below:

Step #1 - "tf plan validate all": Error: Module not found                                                                                                                                 
Step #1 - "tf plan validate all":                                                                                                                                                         
Step #1 - "tf plan validate all": Module "composer" (from composer.tf:1) cannot be found in the module registry                                                                           
Step #1 - "tf plan validate all": at registry.terraform.io.                                                                                                                               
Step #1 - "tf plan validate all":                                                                                                                                                         
Step #1 - "tf plan validate all":  

The composer.tf code looks like this:
module "composer" {
  source  = "terraform-google-modules/composer/google"
  version = "~> 0.1"

  project_id  = module.sandbox_application_project.project_id
  name        = "composer-env-test"
  region       = var.region_default
}

**Comment by bharathkkb** [comment]
Hi @ipv1337 
Thanks for the report, it should be [available now](https://registry.terraform.io/modules/terraform-google-modules/composer/google/latest).
