### ISSUE TITLE
The module only works for region us-central 

### ISSUE THREAD

**Issue by guhcampos** [terraform-google-modules/terraform-google-composer#31]
### TL;DR

The `create_environment` submodule expects a variable `zone` which defaults to `us-central1-f` but the root module never passes this variable down. Changing `region` for anything other than `us-central` therefore issues the following errors:

```
│ Error: googleapi: Error 400: Found 2 problems:
│       1) Provided zone [projects/myproject/zones/us-central1-f] must be contained within Composer location [southamerica-east1].
│       2) Provided subnetwork [projects/myproject/regions/us-central1/subnetworks/myproject-airflow-subnet] must match Composer location [southamerica-east1]., badRequest
```

### Expected behavior

All relevant variables should be passed down from the root module to the `create_environment` submodule.

### Terraform Configuration

```hcl
module "composer" {

  source  = "terraform-google-modules/composer/google"
  version = "~> 2.0"

  project_id = "myproject"
  region     = "southamerica-east1"

  composer_env_name = "myproject-airflow"
  network           = "myproject-airflow-network"
  subnetwork        = "myproject-airflow-subnet"
}
```

### Terraform Version

```sh
1.1.3
```

**Comment by morgante** [comment]
Yes we should pass this down.

**Comment by g-awmalik** [comment]
@morgante - we can close this issue.

**Comment by bharathkkb** [comment]
fixed via https://github.com/terraform-google-modules/terraform-google-composer/pull/35
