### ISSUE TITLE
Update scripts so they can install a Composer 2 environment

### ISSUE THREAD

**Issue by chrisfalter** [terraform-google-modules/terraform-google-composer#32]
### TL;DR

Composer 2 provides a variety of advantages over Composer 1 to organizations running data engineering workloads; among them is a simplified setup that rejects many previous setup parameters and adds a few simpler parameters. The Composer 1 parameters currently in these scripts block the successful installation of a Composer 2 environment. This feature request is asking for an update so that a Composer 2 installation will succeed. 

### Detailed design

```markdown
I suggest the creation of an entirely new directory/folder for Composer 2. This would avoid the need for branching logic (if Composer-1, do x; else if Composer-2, do y). It would probably be simpler to use, as well. 

However, it would also be possible to recognize a Composer 2 installation request by parsing the `image_version` variable, or by defining a new variable called `composer_major_version` (with a default of `"1"`).
```

**Comment by Raj200** [comment]
Any update on this? When we can expect a module for Composer 2.0 ?
