### ISSUE TITLE
DESTROY does not clean up storage bucket and redis disk

### ISSUE THREAD

**Issue by chrisfalter** [terraform-google-modules/terraform-google-composer#33]
### TL;DR

Running the DESTROY does not clean up storage bucket and redis disk associated with the Composer environment.

### Expected behavior

In keeping with infrastructure-as-code principles, I would expect that running DESTROY would clean up all resources associated with the Composer environment, and not leave any to be cleaned up manually afterward.

### Observed behavior

Running the DESTROY does not clean up storage bucket and redis disk associated with the Composer environment.

### Terraform Configuration

```hcl
This buggy behavior occurs with any Terraform configuration.
```

### Terraform Version

```sh
This buggy behavior occurs with any Terraform configuration.
```

**Comment by morgante** [comment]
We do not create any of those resources in this module. You are likely referring to side effects of Cloud Composer, which would need to be addressed in the API itself.

Please open a support case with Google if you have further concerns.
