### ISSUE TITLE
Enable GKE control plane external access on composer

### ISSUE THREAD

**Issue by Rishabh027** [terraform-google-modules/terraform-google-composer#38]
### TL;DR

The feature will enable user to connect to GKE control plane through VM in the same VPC but in different subnet.
This feature can be enabled through console, need a way to enable using terraform

**Comment by jond3k** [comment]
@Rishabh027 can you provide a link to the command you used? My understanding is that the GKE control plane internal IP is only restricted by location [1], not by ranges. Could this be why it's not reachable?

1. https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#cp-global-access
