### ISSUE TITLE
Updating scheduler_count does not update scheduler_count

### ISSUE THREAD

**Issue by mpinkert** [terraform-google-modules/terraform-google-composer#39]
### TL;DR

Changing the value of `scheduler_count` for an existing composer does not change the number of schedulers.  The module updates in place but no change takes no place on the actual Composer.  

The variable works fine in the initial setup.

### Expected behavior

Changing `scheduler_count` from 2 to 3 would update the Composer environment to have 3 composers.

### Observed behavior

The composer environment did not change.

### Terraform Configuration

```hcl
software_config {
      scheduler_count = var.scheduler_count > 0 ? var.scheduler_count : null
      image_version = "composer-1.18.0-airflow-2.2.3"
    }
```

### Terraform Version

```sh
hashicorp/terraform:1.0.1
hashicorp/google v4.14.0
hashicorp/google-beta v4.14.0
hashicorp/kubernetes v2.8.0
hashicorp/template v2.2.0
```

**Comment by rokity** [comment]
Did you tried use not a conditional expression but a static imperative and it changes ?
Like in this example: 
```Terraform
software_config {
      scheduler_count = 4
      image_version = "composer-1.18.0-airflow-2.2.3"
    }
```

**Comment by xi-li-db** [comment]
We noticed the same issue. the plan shows  ~ scheduler_count = 1 -> 2 , however it is not applied

**Comment by rokity** [comment]
I think you can use assign a variable  on your module and create a dependency of it.
