### ISSUE TITLE
kubernetes version selection

### ISSUE THREAD

**Issue by gboto-nauto** [terraform-google-modules/terraform-google-composer#95]
### TL;DR

The terraform google composer module should have the ability to specify which version of kubernetes will be deployed.The only thing you can choose is whether to use composer1 or 2 which gives you the choice between a standard kubernetes installation or autopilot mode.

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/composer_environment.html
```

### Detailed design

```markdown
have the possibility to choose the version as you can do with the following module.

https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/latest/submodules/beta-autopilot-private-cluster?tab=inputs

kubernetes_version string
Description: The Kubernetes version of the masters. If set to 'latest' it will pull latest available version in the selected region.
Default: "latest"
```

**Comment by imrannayer** [comment]
@gboto-nauto cloud composer V2 dont have a parameter for passing GKE autopilot version. Can you check composer document if this is possible. I dont see any option in [composer API](https://cloud.google.com/composer/docs/reference/rest/v1beta1/projects.locations.environments). 

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/composer_environment#argument-reference---cloud-composer-2
